name: TestBuildComponentWindowsInstall
description: First two lines from configureIis.
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: configureIis
        action: ExecutePowerShell
        inputs:
          commands:
            - Install-WindowsFeature -Name Web-Server -IncludeManagementTools
            - Install-WindowsFeature -Name NET-Framework-45-ASPNET,Web-Asp-Net45,Web-Net-Ext45,Web-ISAPI-Ext,Web-ISAPI-Filter